### ISSUE TITLE
About Video Downloading...

### ISSUE THREAD

**Issue by piyushpaghdal** [DevAdeel/Video-Downloader#5]
1. Get Error When Facebook Video Download : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()'

2. Get Error When Instagram Video Download : Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -10

**Comment by DevAdeel** [comment]
This is an old sample project. This may not work now because many platforms has changed their video listing mechanism. You can get an idea of how you can get download link using web scraping by this sample project.
