### ISSUE TITLE
Facebook video url

### ISSUE THREAD

**Issue by mhdaslam790** [DevAdeel/Video-Downloader#8]
Which method is extracting Facebook video URL.can you explain?

**Comment by DevAdeel** [comment]
Hi [Mohammad Aslam Ansari](https://github.com/mhdaslam790),

You can checkout [FbVideoDownloader.java](https://github.com/DevAdeel/Video-Downloader/blob/master/app/src/main/java/com/example/videodownloader/Models/FbVideoDownloader.java) to get an idea of downloading video from Facebook URL.

**NOTE**
This method will not work anymore.
