### ISSUE TITLE
Most of the methods no longer work

### ISSUE THREAD

**Issue by Arsalan-Tahir** [DevAdeel/Video-Downloader#9]
Insta downloader doesn't work
Tiktok doesn't work
Twitter doesn't work
..

**Comment by DevAdeel** [comment]
Hi Arslan,

Thanks for taking interest in this project but as you can see last commit is 2 years ago and It is clearly mentioned in readme that this project is no longer being maintained. These methods were working fine 2 years ago and now maybe they have changed their video URLs etc. But you can get the idea of web scraping from this project.

Thanks!
